### ISSUE TITLE
Reflection warnings

### ISSUE THREAD

**Issue by seancorfield** [congomongo/congomongo#113]
Take another run at removing reflection warnings:

Reflection warning, somnium/congomongo.clj:106 - call to authenticate can't be resolved.
Reflection warning, somnium/congomongo.clj:124 - call to startsWith can't be resolved.
Reflection warning, somnium/congomongo.clj:383 - call to distinct can't be resolved.
Reflection warning, somnium/congomongo.clj:583 - call to createFile can't be resolved.
Reflection warning, somnium/congomongo.clj:627 - call to findOne can't be resolved.
Reflection warning, somnium/congomongo.clj:629 - call to writeTo can't be resolved.
Reflection warning, somnium/congomongo.clj:635 - call to findOne can't be resolved.

**Comment by jheander** [comment]
Only warnings left now are motivated by method accepting multiple data types and looking them up manually will be the same or higher penalty than reflection.
