### ISSUE TITLE
Suggestion: make connection a record implementing `Closeable`, hence work `with-open`

### ISSUE THREAD

**Issue by mjwillson** [congomongo/congomongo#127]
This is a nice little trick I've used when wrapping java classes for open resources:

``` clojure
(defrecord Connection [mongo db]
  java.io.Closeable
  (close [conn] (close-connection conn)))

(defn make-connection
  ...
  (->Connection mongo db))

(with-open [conn (make-connection ...)]
  ;; do stuff
  )
```

Not sure how this would interact with the thread-local connection stuff in congomongo, but could allow for a rather nice and idiomatic way to use these connections?

**Comment by jheander** [comment]
Won't fix this right now since it requires a complete API rewrite.
