### ISSUE TITLE
:errors-ignored write concern

### ISSUE THREAD

**Issue by Engelberg** [congomongo/congomongo#159]
README claims there is a write concern option called :errors-ignored, but in fact, no such option is supported in the congomongo code.

In the meantime, is there a workaround that will allow me to mass-insert! a bunch of data into a collection with a unique index, and gracefully ignore any data that can't be added due to a duplicate value on that unique index. Right now, it throws an error which prevents the other valid data from being added.

**Comment by jheander** [comment]
Hi!
It seems that the :errors-ignored write concern was deprecated by the underlying Java driver some versions back. You can choose to either use the :unacknowledged write concern or performing an unordered bulk operation instead.

**Comment by jheander** [comment]
I have updated the README to omit the deprecated option.
