### ISSUE TITLE
`update!` uses `upsert` whereas `fetch-and-modify` uses `upsert?`

### ISSUE THREAD

**Issue by acron0** [congomongo/congomongo#163]
This catches me out regularly. IMO boolean args should always suffix with `?` so I would propose `update!` is fixed to reflect this. I would also apply this to `multiple` which also lacks `?`. I am happy to make PR but what is the approach here? Support both versions so as to not break?

**Comment by jheander** [comment]
Yeah, this trips me up sometimes too but we would definitely need to support both versions during some transition period so it does not break existing code.

**Comment by marksto** [comment]
It has made its way into the `master` with the https://github.com/congomongo/congomongo/commit/44ad3c13d37237e29f113dae23938823497abd58. Will be released whenever the rest of the functions (`distinct-values`, `insert!`, `fetch-and-modify`, `aggregate`, and `command`) are upgraded to use the `DBCollection` v3.4 API.

**Comment by jheander** [comment]
Released in v2.4.0
