### ISSUE TITLE
Requesting array index in a query

### ISSUE THREAD

**Issue by gukiboy** [congomongo/congomongo#172]
In Mongo querying we can do something like:
`{'person.cars.1': {$exists: true}}`

I tried to do it in Congomongo like this:
`{'person.cars.1' {:$exists true}}`

But it did not work. Is it possible in Congomongo?

Thanks in advance!

**Comment by jheander** [comment]
Hi!
I have tried some similar queries and it seems to work. Could you send a bit more complete example of what's happening and what the difference is when you're running the same query in the console?
// Johan

**Comment by gukiboy** [comment]
Hello, I solved it with another approach, but I'll try again. I probably commited a mistake. Thank you for the answer!
